WIP: Points and levels
tdd-pingis/tdd-pingpong pull request #188
Opened 2017-08-24 08:51 UTC by lramirez

2017-08-25 10:23 UTC, dwarfcrank commented on src/main/java/pingis/entities/TaskInstance.java
> -
Unnecessary whitespace change.

2017-08-25 10:23 UTC, dwarfcrank commented on src/main/java/pingis/entities/User.java
>    @Min(LEVEL_MIN_VALUE)
These constraints should be either removed or updated.

2017-08-25 10:44 UTC, dwarfcrank commented on src/main/java/pingis/services/UserService.java
> +    for (int i = 1; i <= numberOfLevels; i++) {
Couldn't this be computed with logarithms instead, e.g. `level = log(points, base) - log(pointsForFirstLevel, base)`?

2017-08-25 10:45 UTC, dwarfcrank commented on src/main/java/pingis/services/UserService.java
> +    for (int i = 1; i <= numberOfLevels; i++) {
Also needs more tests.

2017-08-25 10:46 UTC, dwarfcrank commented on src/test/java/pingis/entities/UserTest.java
>      final double level = 0.001;
Why is this named `level` when it's used as the minimum delta for float-point comparisons?

2017-08-27 15:11 UTC, lramirez commented
Accidentally included commits from another branch.  Merge this one after the other.

2017-08-27 21:36 UTC, Heliozoa requested changes

2017-08-27 21:36 UTC, Heliozoa commented on src/main/java/pingis/services/UserService.java
> +  private final float base = 1.2f;
Unused variables

2017-08-27 21:36 UTC, Heliozoa commented on src/test/java/pingis/entities/UserTest.java
>      final double level = 0.001;
^

2017-08-27 21:36 UTC, Heliozoa commented on src/main/java/pingis/services/DataImporter.java
> +  private static final int IMPLEMENTATION_USER_LEVEL = 1000;
Unused variables? Also, the name should probably be changed to points.

2017-08-27 21:36 UTC, Heliozoa commented on src/main/java/pingis/entities/TaskInstance.java
> +
Whitespace change

2017-08-27 21:36 UTC, Heliozoa commented on src/main/java/pingis/entities/Task.java
> +  public static final int LEVEL_MAX_VALUE = 200000;
Should probably be renamed to points

2017-08-28 07:23 UTC, dwarfcrank commented on src/test/java/pingis/services/TaskInstanceServiceTest.java
> +    assertTrue(oldPoints < testUser.getPoints());
This test would be better if you calculated the expected number of points and used `assertEquals`.

2017-08-28 09:20 UTC, Heliozoa approved these changes

2017-08-28 09:22 UTC, merged